name: Run tests in embbedded python

env:
  PIP_DISABLE_PIP_VERSION_CHECK: "1"
  PIP_NO_PYTHON_VERSION_WARNING: "1"

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  build:
    name: Build binary for ${{ matrix.runs-on }}
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        runs-on:
          - windows-latest
          # - ubuntu-20.04
          # - macos-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # get correct version
      - uses: actions/setup-python@v5
        with:
          # Double-check latest version supported by PyOxidizer:
          # https://github.com/indygreg/PyOxidizer/releases/
          python-version: "3.10"

      - name: Install pyoxidizer
        run: |
          python -m pip install pyoxidizer

      - name: run tests
        shell: bash
        run: |
          pyoxidizer run
